### ISSUE TITLE
Strict-Transport-Security: Preloading should be opt-in

### ISSUE THREAD

**Issue by jamesmacwhite** [GetPageSpeed/ngx_security_headers#13]
It's potentially dangerous for the default to include preload in the header, because of any misconfiguration or mistake. If a browser adds a domain into the preload list without the proper configuration or requirements, that domain will be broken, unless removed from the preload list which can take time and is a manual process.

https://hstspreload.org/#opt-in

Having preload added to the header should be an opt-in setting, rather than hard coded into the module by default. It also doesn't make sense for an nginx server that may just serving subdomains. The `preload` value would only apply on the root domain.

**Comment by dvershinin** [comment]
@jamesmacwhite I would rather keep the current default behavior as is because it depends on how you interpret the opt-in behavior:

If we consider that the primary software providing ability to send HSTS header is NGINX (and not the module), then indeed it (NGINX) does not enable it by default. Then you *enable* it by using this module (opt-in through installing the module). 

Implementing true opt-in in the module itself is not desirable, for having an extra configuration directive has to be added 99% of the time. Most people will want to be preloaded for performance reasons and would have to add an extra configuration directive to opt-in.

A solution I see is opt-out behavior and documented this atop the README. 

As far as adding `preload` to root domain and not subdomains, pull requests are welcome. I'd merge if it doesn't have a substantial performance impact. Mind edge cases for TLDs like example.co.uk. It's not easy to say "it is root domain" by merely checking the number of dots. So I'd keep the current behavior of adding it for subdomains because nothing would break from doing so, although it's not as perfect as it may be :)

**Comment by jamesmacwhite** [comment]
I think not having preload hard coded is a good move, which I can see you've implemented a way to turn it off. That works for me.
